---
- name: Deploy auth client
  hosts: master[0]
  pre_tasks:
  - include_vars: ../../common/container-list.json
  vars:
  - kube_image_prefix: "{{ docker_registry_host | default(default_registry) }}/"
  - image: "{{ kube_image_prefix }}{{ containers.erikube.auth_client }}"
  - auth_client_image: "{{ auth_client_ext_image | default(image) }}"
  - auth_client_action: deploy
  - auth_client_cpu_req: "{{ ccd_auth_client_cpu_req | default('50m') }}"
  - auth_client_mem_req: "{{ ccd_auth_client_mem_req | default('30Mi') }}"
  - auth_client_cpu_limit: "{{ ccd_auth_client_cpu_limit | default('100m') }}"
  - auth_client_mem_limit: "{{ ccd_auth_client_mem_limit | default('60Mi') }}"
  roles:
  - role: auth-client
    when: auth_client_enabled is defined and auth_client_enabled
