---
- name: Deploy calicoctl
  hosts: master[0]
  pre_tasks:
  - include_vars: ../../common/container-list.json
  vars:
  - kube_image_prefix: "{{ docker_registry_host | default(default_registry) }}/"
  - image: "{{ kube_image_prefix }}{{ containers.calico.ctl }}"
  - calicoctl_image: "{{ calicoctl_ext_image | default(image) }}"
  - calicoctl_action: deploy
  - kubectl: /usr/local/bin/kubectl --kubeconfig /etc/kubernetes/admin.conf
  roles:
  - role: erikube-defaults
  - role: calicoctl