---
- name: Create etcd CA
  hosts: etcd
  become: yes
  any_errors_fatal: true
  vars:
    etcd_ca_host: "{{ groups.etcd.0 }}"
  tasks:
    - include_role:
        name: etcd
        tasks_from: ca-deploy

- name: Deploy etcd cluster
  hosts: etcd
  become: yes
  any_errors_fatal: true
  vars:
    etcd_ca_host: "{{ groups.etcd.0 }}"
    etcd_peers: "{{ groups.etcd | default([], true) }}"
  tasks:
    - include_role:
        name: etcd
        tasks_from: deploy
