---
- name: Gather facts as non root
  hosts: master[0]
  gather_facts: yes

- name: Configure ISP Logger Service
  hosts: master[0]
  become: yes
  roles:
  - erikube-defaults
  tasks:
    - name: Create ISP Logger secret for accessing local registry
      shell: |
        {{ kubectl }} create secret docker-registry local-registry-secret \
        --docker-server={{ 'registry.eccd.local:5000' if local_registry_user is defined and local_registry_user != "" else 'null.eccd.local' }} \
        --docker-username={{ local_registry_user if local_registry_user is defined and local_registry_user != "" else 'null' }} \
        --docker-password={{ local_registry_password if local_registry_password is defined and local_registry_password != "" else 'nopassword' }} -n monitoring \
        --dry-run=client -o yaml | {{ kubectl }} apply -f -
      register: result
      become: true
      retries: "{{ kubectl_retry_count }}"
      delay: "{{ kubectl_retry_delay }}"
      until: result.rc == 0
      ignore_errors: True
