---
- name: Deploy Rook cluster
  hosts: master[0]
  become: yes
  pre_tasks:
    - include_vars: ../../common/container-list.json
  vars:
    - kube_image_prefix: "{{ docker_registry_host | default(default_registry) }}/"
    - tarball_name: "{{ helm_charts.rook_cluster.name + '-' + helm_charts.rook_cluster.version + '.tgz' }}"
    - mgr_resources_default:
        limits:
          cpu: "1000m"
          memory: "1024Mi"
        requests:
          cpu: "500m"
          memory: "512Mi"
    - mon_resources_default:
        limits:
          cpu: "2000m"
          memory: "2048Mi"
        requests:
          cpu: "1000m"
          memory: "1024Mi"
    - osd_resources_default:
        limits:
          cpu: "2000m"
          memory: "4096Mi"
        requests:
          cpu: "1000m"
          memory: "4096Mi"
    - mds_resources_default:
        limits:
          cpu: "500m"
          memory: "1024Mi"
        requests:
          cpu: "500m"
          memory: "1024Mi"
  roles:
    - erikube-defaults
    - role: helm-chart-provisioner
      when: rook.enabled | default(false)
      vars:
        - chart_name: "rook"
        - tarball: "{{ helm_chart_loc }}/{{ tarball_name }}"
        - state: installed
        - kube_namespace: "rook-ceph"
        - values:
            imagePullSecrets:
              - name: local-registry-secret
            cephClusterSpec:
              cephVersion:
                image: "{{ kube_image_prefix }}{{ containers.erikube.rook_ceph_sbd }}"
              storage:
                useAllNodes: true
                useAllDevices: "{{ rook.storage.all | default(true) }}"
                devicePathFilter: "{{ rook.storage.filter | default('') }}"
              resources:
                mgr: "{{ rook.resources.mgr | default(mgr_resources_default) }}"
                mon: "{{ rook.resources.mon | default(mon_resources_default) }}"
                osd: "{{ rook.resources.osd | default(osd_resources_default) }}"
            toolbox:
              image: "{{ kube_image_prefix }}{{ containers.erikube.rook_operator_sbd }}"
            configOverride: |
                [global]
                public network = {{ rook.public_cidr }}
                cluster network = {{ rook.cluster_cidr | default(rook.public_cidr)}}
                public addr = ""
                cluster addr = ""
            cephBlockPools:
              - name: ceph-network-block
                spec:
                  failureDomain: host
                  replicated:
                    size: 3
                storageClass:
                  enabled: true
                  name: "{{ rook.rbd.name | default('network-block')}}"
                  isDefault: true
                  reclaimPolicy: Delete
                  allowVolumeExpansion: true
                  parameters:
                    imageFormat: "2"
                    imageFeatures: layering
                    csi.storage.k8s.io/provisioner-secret-name: rook-csi-rbd-provisioner
                    csi.storage.k8s.io/provisioner-secret-namespace: rook-ceph
                    csi.storage.k8s.io/controller-expand-secret-name: rook-csi-rbd-provisioner
                    csi.storage.k8s.io/controller-expand-secret-namespace: rook-ceph
                    csi.storage.k8s.io/node-stage-secret-name: rook-csi-rbd-node
                    csi.storage.k8s.io/node-stage-secret-namespace: rook-ceph
                    csi.storage.k8s.io/fstype: "{{ rook.rbd.fstype | default('ext4') }}"
            cephFileSystems:
              - name: ceph-filesystem
                spec:
                  metadataPool:
                    replicated:
                      size: 3
                  dataPools:
                    - failureDomain: host
                      replicated:
                        size: 3
                  metadataServer:
                    activeCount: 1
                    activeStandby: false
                    resources: "{{ rook.resources.mds | default(mds_resources_default) }}"
                storageClass:
                  enabled: true
                  isDefault: false
                  name: "{{ rook.cephfs.name | default('network-file')}}"
                  reclaimPolicy: Delete
                  allowVolumeExpansion: true
                  parameters:
                    csi.storage.k8s.io/provisioner-secret-name: rook-csi-cephfs-provisioner
                    csi.storage.k8s.io/provisioner-secret-namespace: rook-ceph
                    csi.storage.k8s.io/controller-expand-secret-name: rook-csi-cephfs-provisioner
                    csi.storage.k8s.io/controller-expand-secret-namespace: rook-ceph
                    csi.storage.k8s.io/node-stage-secret-name: rook-csi-cephfs-node
                    csi.storage.k8s.io/node-stage-secret-namespace: rook-ceph
