---
- name: Gather facts as non root
  hosts: [master]
  gather_facts: yes

- hosts: [master]
  become: yes
  pre_tasks:
  - name: default vars
    include_vars:
      file: roles/kube-common/defaults/main.yml

  roles:
    - erikube-defaults
    - kube-secret-key-rotate
