---
- include_vars: "{{ item }}"
  with_first_found:
    - files:
      - "../vars/{{ ansible_distribution }}.yml"
      - "../vars/{{ ansible_os_family }}.yml"
      skip: True

- name: Make runc symlink to /usr/bin
  file: src=/usr/local/bin/runc dest=/usr/bin/runc state=link
  when: ansible_distribution == "CentOS" or ansible_distribution == "Ubuntu"

- name: Make runc symlink to /usr/sbin
  file: src=/usr/local/bin/runc dest=/usr/sbin/runc state=link
  when: ansible_distribution == "SLES"

- name: Fetch runc version
  shell: "runc --version"
  register: runc_version_out
  become: true
  changed_when: false
  ignore_errors: yes

- name: Print version from runc binary before possible upgrade
  debug:
    msg: "{{ runc_version_out.stdout.split('\n') }}"

- block:
  - name: "Do OS specific installation steps of runc for {{ ansible_distribution }}"
    include_tasks: "{{ runc_install_item }}"
    with_first_found:
      - files:
        - "install-{{ ansible_distribution }}.yml"
        - "install-{{ ansible_os_family }}.yml"
        skip: True
    loop_control:
      loop_var: runc_install_item

  when: not is_atomic and ansible_os_family != 'Debian'
