---
- name: Create temp workspace directory
  command: mktemp -d /tmp/erikube-k8s-XXXXXX
  register: mktemp
  changed_when: False

- set_fact:
    k8s_file_loc: "{{ mktemp.stdout }}"
    etcd_cert_config_dir: "{{ mktemp.stdout }}/certs"

- name: Create client etcd certificates
  vars:
    etcd_cert_prefix: "etcd-"
    etcd_cert_subdir: "calico"
    etcd_client_cert_cn: "calico"
  import_role:
    name: etcd
    tasks_from: get-client-cert

- name: Copy etcd key file
  become: yes
  copy:
    src: "{{ etcd_cert_config_dir }}/etcd-client.key"
    dest: "{{ etcd_cert_config_dir }}/etcd-key"
    remote_src: true
    mode: 0600

- name: Copy etcd cert file
  become: yes
  copy:
    src: "{{ etcd_cert_config_dir }}/etcd-client.crt"
    dest: "{{ etcd_cert_config_dir }}/etcd-cert"
    remote_src: true
    mode: 0644

- name: Copy etcd ca file
  become: yes
  copy:
    src: "{{ etcd_cert_config_dir }}/etcd-ca.crt"
    dest: "{{ etcd_cert_config_dir }}/etcd-ca"
    remote_src: true
    mode: 0644

- name: Delete unused files
  become: yes
  file:
    path: "{{ etcd_cert_config_dir }}/{{ item }}"
    state: absent
  with_items:
    - etcd-client.key
    - etcd-client.crt
    - etcd-ca.crt
    - etcd-client.csr

- name: "Update secret with the renewed certificates"
  shell:
    executable: /bin/bash
    cmd:  "{{ kubectl }} --namespace kube-system create secret generic {{ calico_secret_name }} \
          --from-file={{ etcd_cert_config_dir }} --dry-run=client -o yaml | {{ kubectl }} apply -f -"
  become: yes
  register: cert_update
  retries: "{{ kubectl_retry_count }}"
  delay: "{{ kubectl_retry_delay }}"
  until: cert_update.rc == 0

- name: Delete temp directory
  file:
    name: "{{ mktemp.stdout }}"
    state: absent
  become: yes
  changed_when: False
