---
- name: Delete existing asih nels secret
  command: "{{ kubectl }} -n {{ kube_namespace }} delete secret {{ asih_nels_secret }} --ignore-not-found"
  become: yes
  register: result
  retries: "{{ kubectl_retry_count }}"
  delay: "{{ kubectl_retry_delay }}"
  until: (result.rc == 0 or "not found" in result.stderr)

- name: Create empty secret for asih
  block:
    - name: Create temp directory
      file:
        path: "{{ item }}"
        state: directory
        mode: 0700
        owner: root
        group: root
        recurse: yes
      with_items:
        - "{{ dir }}"

    - name: Create empty data file
      copy:
        dest: "{{ item }}/data"
        content: ""
        force: no
      with_items:
        - "{{ dir }}"

    - name: Create secret from asih nels CA cert
      shell: "{{ kubectl }} -n {{ kube_namespace }} create secret generic {{ asih_nels_secret }} --from-file={{ dir }}/data"
      register: result
      retries: "{{ kubectl_retry_count }}"
      delay: "{{ kubectl_retry_delay }}"
      until: result.rc == 0

  when: ccd_app_sys_info_ca is not defined

- name: Create secret from asih nels ca file
  block:
    - name: Create temp directory
      file:
        path: "{{ item }}"
        state: directory
        mode: 0700
        owner: root
        group: root
        recurse: yes
      with_items:
        - "{{ dir }}"

    - name: Copy asih ca
      copy:
        content: "{{ ccd_app_sys_info_ca }}"
        dest: "{{ dir }}/ca.crt.pem"

    - name: Create secret to kube-system namespace
      shell: "{{ kubectl }} -n {{ kube_namespace }} create secret generic {{ asih_nels_secret }} --from-file={{ dir }}/ca.crt.pem"
      register: result
      retries: "{{ kubectl_retry_count }}"
      delay: "{{ kubectl_retry_delay }}"
      until: result.rc == 0

  when: ccd_app_sys_info_ca is defined

- name: Delete temp directory
  file:
    name: "{{ dir }}"
    state: absent
  changed_when: False
