
- name: Rewrite all secrets
  shell: "{{ kubectl }} get secrets --all-namespaces -o json | {{ kubectl }} replace -f -"
  register: cmd_status
  until: cmd_status.rc == 0
  retries: 10
  delay: 15
  become: yes

