---
- name: Check for a supported Operating System
  block:
  - assert:
      that: ansible_os_family == 'RedHat' and ansible_distribution_major_version == '7'
      msg: "The only supported platforms for this release are CentOS 7, RHEL 7.4, Ubuntu 20.04 and SLES 15"
    when: ansible_os_family == 'RedHat'

  - assert:
      that: ansible_distribution == 'Ubuntu' and ansible_distribution_major_version == '20'
      msg: "The only supported platforms for this release are CentOS 7, RHEL 7.4, Ubuntu 20.04 and SLES 15"
    when: ansible_distribution == 'Ubuntu'

  - assert:
      that: ansible_distribution == 'SLES' and ansible_distribution_version | regex_search('15')
      msg: "The only supported platforms for this release are CentOS 7, RHEL 7.4, Ubuntu 20.04 and SLES 15"
    when: ansible_distribution == 'SLES'
