- set_fact:
    pmbr_conf: "{{ pmbr_config }}"

- name: Check for existing secret
  command: "{{ kubectl }} -n {{ pmbr_namespace }} get secret {{ pmbr_secret }}"
  register: get_secret
  failed_when: false
  changed_when: false
  retries: "{{ kubectl_retry_count }}"
  delay: "{{ kubectl_retry_delay }}"
  until: (get_secret.rc == 0 or "not found" in get_secret.stderr)

- block:
  - name: Create temporary config directory
    tempfile:
      state: directory
      suffix: pmbr
    register: tempdir_pmbr

  - name: Store pmbr user config to temporary file
    copy:
      content: "{{ pmbr_conf }}"
      dest: "{{ tempdir_pmbr.path }}/users.yaml"

  - name: Set no files
    set_fact:
      filelist: ""

  - name: Create config content string
    set_fact:
      filelist: "{{ filelist }} --from-file={{ tempdir_pmbr.path }}/users.yaml"

  - name: Create Postgres secret in k8s cluster
    shell: >-
      {{ kubectl }} create secret generic pm-br-sftp-users-secret --namespace {{ pmbr_namespace }} {{ filelist }}
    register: result
    retries: "{{ kubectl_retry_count }}"
    delay: "{{ kubectl_retry_delay }}"
    until: result.rc == 0

  - name: Delete temporary file
    file:
      path: "{{ tempdir_pmbr.path }}"
      state: absent
    when: tempdir_pmbr.path is defined

  when: (get_secret.rc != 0 and "not found" in get_secret.stderr)
