---
# this task isolated so play can serialize it
- name: Install and setup docker
  become: yes
  any_errors_fatal: true
  block:
    - include_role:
        name: docker
        tasks_from: install
    - include_role:
        name: docker