---
- name: Get IP of ingress controller
  command: "{{ kubectl }} get service --namespace {{ default_ingress_namespace | default('ingress-nginx') }} \
           {{ default_ingress_service | default('ingress-nginx') }} -o jsonpath='{.spec.clusterIP}'"
  register: get_ingress_ctrl_ip
  when: not image_based_deployment | default(false) | bool
  become: yes
  retries: "{{ kubectl_retry_count }}"
  delay: "{{ kubectl_retry_delay }}"
  until: (get_ingress_ctrl_ip.rc == 0 or "not found" in get_ingress_ctrl_ip.stderr)

- name: Add dex hostname to point to ingress controller in /etc/hosts
  lineinfile:
    path: /etc/hosts
    line: "{{ get_ingress_ctrl_ip.stdout }}  {{ dex_ingress_host | default('auth.eccd.local') }}"
    state: present
  become: true
  delegate_to: "{{ item }}"
  loop: "{{ groups['master'] }}"
  become: yes
  when:
    - not image_based_deployment | default(false) | bool
    - dex_action != "purge"

- name: Remove dex hostname from /etc/hosts
  lineinfile:
    path: /etc/hosts
    line: "{{ get_ingress_ctrl_ip.stdout }}  {{ dex_ingress_host | default('auth.eccd.local') }}"
    state: absent
  become: true
  delegate_to: "{{ item }}"
  loop: "{{ groups['master'] }}"
  become: yes
  when:
    - not image_based_deployment | default(false) | bool
    - dex_action == "purge"
