---
- name: Check variables required to delete secret is defined
  assert:
    that:
      - tls_secret is defined
- name: Delete tls secret resource if exists
  shell: "{{ kubectl }} delete secret {{ tls_secret }} -n monitoring --ignore-not-found"
  ignore_errors: yes
  register: result
  retries: "{{ kubectl_retry_count }}"
  delay: "{{ kubectl_retry_delay }}"
  until: (result.rc == 0 or "not found" in result.stderr)
