---
- name: Remove container registry hostname and ingress controller IP from /etc/hosts
  lineinfile:
    path: /etc/hosts
    regexp: "{{ container_registry_hostname | default('k8s-registry.eccd.local') }}"
    state: absent
  become: true
  delegate_to: "{{ item }}"
  loop: "{{ groups['master'] + groups['worker'] }}"
  when: not image_based_deployment | default(false) | bool

