- name: Get the list of the installed packages
  package_facts:
    manager: auto
  when: (ansible_distribution == "CentOS" or ansible_distribution == "Ubuntu")

- name: Install httpd-tools (Centos)
  package:
    name: "httpd-tools"
    state: present
    update_cache: yes
  register: result
  until: result is success
  retries: "{{ install_os_packages_retries if (install_os_packages_retries is defined) else 0 }}"
  delay: "{{ install_os_packages_delay if (install_os_packages_delay is defined) else 5 }}"
  ignore_errors: yes
  when: (ansible_distribution == "CentOS" and "httpd-tools" not in ansible_facts.packages)

- name: Install apache2-utils (Ubuntu)
  package:
    name: "apache2-utils"
    state: present
    update_cache: yes
  register: result
  until: result is success
  retries: "{{ install_os_packages_retries if (install_os_packages_retries is defined) else 0 }}"
  delay: "{{ install_os_packages_delay if (install_os_packages_delay is defined) else 5 }}"
  ignore_errors: yes
  when: (ansible_distribution == "Ubuntu" and "apache2-utils" not in ansible_facts.packages)
