---
etcd_service: "etcd_container"
etcd_systemd_dir: "/etc/systemd/system"

# CA variables
etcd_ca_dir: "{{ etcd_conf_dir}}/ca"
etcd_generated_certs_dir: "{{ etcd_conf_dir }}/generated_certs"
etcd_ca_cert: "{{ etcd_ca_dir }}/ca.crt"
etcd_ca_key: "{{ etcd_ca_dir }}/ca.key"
etcd_openssl_conf: "{{ etcd_ca_dir }}/openssl.cnf"
etcd_ca_crl_dir: "{{ etcd_ca_dir }}/crl"
etcd_ca_new_certs_dir: "{{ etcd_ca_dir }}/certs"
etcd_ca_db: "{{ etcd_ca_dir }}/index.txt"
etcd_ca_serial: "{{ etcd_ca_dir }}/serial"
etcd_ca_crl_number: "{{ etcd_ca_dir }}/crlnumber"
etcd_ca_default_days: 7300

# Server variables
etcd_conf_dir: "/etc/etcd"
etcd_conf_file: "{{ etcd_conf_dir }}/etcd.conf"
etcd_ca_file: "{{ etcd_conf_dir }}/ca.crt"
etcd_cert_file: "{{ etcd_conf_dir }}/server.crt"
etcd_key_file: "{{ etcd_conf_dir }}/server.key"
etcd_csr_file: "{{ etcd_conf_dir }}/server.csr"
etcd_peer_ca_file: "{{ etcd_conf_dir }}/ca.crt"
etcd_peer_cert_file: "{{ etcd_conf_dir }}/peer.crt"
etcd_peer_key_file: "{{ etcd_conf_dir }}/peer.key"
etcd_peer_csr_file: "{{ etcd_conf_dir }}/peer.csr"
etcd_data_dir: '/var/lib/etcd/'

etcd_service_file: "{{ etcd_systemd_dir }}/{{ etcd_service }}.service"

etcd_client_port: 2379
etcd_peer_port: 2380

etcd_initial_cluster_state: new
etcd_initial_cluster_token: etcd-cluster-1

etcd_initial_advertise_peer_urls: "https://{{ etcd_ip | ipwrap }}:{{ etcd_peer_port }}"
etcd_listen_peer_urls: "https://{{ etcd_ip | ipwrap }}:{{ etcd_peer_port }}"
etcd_advertise_client_urls: "https://{{ etcd_ip | ipwrap }}:{{ etcd_client_port }}"
etcd_listen_client_urls: "https://{{ etcd_ip | ipwrap }}:{{ etcd_client_port }}"

new_etcd_image: "{{ etcd_image }}"
etcd_hostname: "{{ ansible_hostname }}"
etcd_ip: "{{ hostvars[inventory_hostname].k8s_ip_address }}"

etcd_SAN_peers: "{% for host in etcd_peers %}DNS:{{ hostvars[host]['ansible_hostname'] }},IP:{{ hostvars[host].k8s_ip_address }}{% if not loop.last -%},{%- endif -%}{% endfor %}"

etcd_cipher_suites: 'TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_RSA_WITH_AES_256_GCM_SHA384,TLS_RSA_WITH_AES_128_GCM_SHA256,TLS_RSA_WITH_AES_128_CBC_SHA,TLS_RSA_WITH_AES_256_CBC_SHA'