---

- name: Delete NRI TLS Secret
  shell: "{{ kubectl }} delete secret -n kube-system network-resources-injector"

- name: Get timestamp to use as restart annotation
  command: date +%Y%m%d%H%M%S
  register: timestamp

- name: Rolling upgrade of network-resources-injector pods
  shell: "{{ kubectl }} patch deploy -n kube-system network-resources-injector -p '{\"spec\":{\"template\":{\"metadata\":{\"annotations\":{\"certs-restart\": \"{{ timestamp.stdout }}\"}}}}}';"

- name: Check NRI TLS Secret exists
  shell: "{{ kubectl }} get secret -n kube-system network-resources-injector"
  retries: 60
  delay: 1
  register: nri_secret
  until: nri_secret.rc == 0