---
- name: Setup vagrant networking
  become: true
  include_tasks: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml" 

- name: Setup OS specific services and packages
  become: true
  include_tasks: "{{ item }}" 
  with_first_found:
    - files:
      - "{{ ansible_distribution }}.yml" 
      skip: true
