---

- name: Add Docker-CE Repository
  get_url:
    url: https://download.docker.com/linux/centos/docker-ce.repo
    dest: /etc/yum.repos.d/docker-ce.repo

# See https://github.com/moby/moby/issues/33930#issuecomment-312782998
- name: Copy yum.conf for editing
  copy:
    src: "/etc/yum.conf"
    dest: "/etc/yum_docker.conf"
    remote_src: yes

- name: Edit copy of yum.conf to set obsoletes=0
  lineinfile:
    path: "/etc/yum_docker.conf"
    state: present
    regexp: '^obsoletes='
    line: 'obsoletes=0'

- name: Install Docker and pre-reqs
  yum:
    name: "{{ docker_packages }}"
    conf_file: "/etc/yum_docker.conf"
    update_cache: yes
  register: result
  until: result is success
  retries: "{{ docker_install_retries if (docker_install_retries is defined) else 0 }}"
  delay: "{{ docker_install_retry_delay if (docker_install_retry_delay is defined) else 5 }}"