---
- name: Cron job to store kubeadm token in keyvault
  block:
  - name: Copy kubeadm token script to first master
    copy:
      src: "{{ autoscale_token_cron_script }}"
      dest: /usr/local/bin/kubeadm-token.sh
      owner: root
      group: root
      mode: 0755

  - name: Generate and store an initial token
    shell: /usr/local/bin/kubeadm-token.sh

  - name: Add cron job for regenerating and storing kubeadm token
    cron:
      name: "kubeadm token for autoscaling"
      user: root
      hour: "*/24"
      job: "/usr/local/bin/kubeadm-token.sh"

  - block:
    - name: Add docker registry user to keyvault
      shell: az keyvault secret set --vault-name "{{ autoscale_keyvault }}" --name docker-registry-user --value {{ docker_registry_user }}
    - name: Add docker registry user to keyvault
      shell: az keyvault secret set --vault-name "{{ autoscale_keyvault }}" --name docker-registry-pwd --value {{ docker_registry_pwd }}
    when: azure_enable_cloud_provider | default('false') | bool

  become: yes
  delegate_to: "{{ groups.master.0 }}"
  run_once: true
