---
- name: Check kubernetes paths exist
  stat:
    path: "{{ item }}"
  with_items: "{{ kube_backup_paths }}"
  register: backup_dirs_st

- fail:
    msg: "{{ item.item }} does not exist"
  with_items: "{{ backup_dirs_st.results }}"
  when: not item.stat.exists

- set_fact:
    backup_files: "{{ backup_files }} + {{ kube_backup_paths }}"
