---

- block:
  - name: Install EPEL repo.
    yum:
      name: epel-release
      state: present

  - name: Install dependencies packages (yum)
    become: true
    yum:
      name: "{{item}}"
      state: present
      update_cache: yes
    with_items:
    - python-pip
    - python-devel
    - gcc
    - bind-utils
  when: ansible_distribution == "CentOS" or ansible_distribution == "RedHat"

- name: Install dependencies packages (apt)
  become: true
  apt:
    name: "{{item}}"
    state: present
  with_items:
  - python3-pip
  when: ansible_distribution == "Debian" or ansible_distribution == "Ubuntu"

- name: Install python lib
  become: true
  pip:
    name: "{{item}}"
  with_items:
    - ansible
    - shade
