---
- name: Create temp workspace directory
  command: mktemp -d /tmp/erikube-k8s-XXXXXX
  register: mktemp
  changed_when: False

- set_fact:
    etcd_cert_config_dir: "{{ mktemp.stdout }}/certs"

- name: "Check for existing secret {{ victoria_metrics_secret_name }}"
  command: "{{ kubectl }} --namespace {{ victoria_metrics_namespace }} get secret {{ victoria_metrics_secret_name }}"
  become: yes
  register: get_secret
  failed_when: get_secret.rc != 0 and not "NotFound" in get_secret.stderr
  changed_when: false

- block:
  - name: Create client etcd certificates (victoria_metrics)
    vars:
      etcd_cert_prefix: "etcd-"
      etcd_cert_subdir: "victoria_metrics"
      etcd_client_cert_cn: "victoria_metrics"
    import_role:
      name: etcd
      tasks_from: get-client-cert

  - name: Copy etcd key file
    become: yes
    copy:
      src: "{{ etcd_cert_config_dir }}/etcd-client.key"
      dest: "{{ etcd_cert_config_dir }}/etcd-key"
      remote_src: true
      mode: 0600

  - name: Copy etcd cert file
    become: yes
    copy:
      src: "{{ etcd_cert_config_dir }}/etcd-client.crt"
      dest: "{{ etcd_cert_config_dir }}/etcd-cert"
      remote_src: true
      mode: 0644

  - name: Copy etcd ca file
    become: yes
    copy:
      src: "{{ etcd_cert_config_dir }}/etcd-ca.crt"
      dest: "{{ etcd_cert_config_dir }}/etcd-ca"
      remote_src: true
      mode: 0644

  - name: Delete unused files
    become: yes
    file:
      path: "{{ etcd_cert_config_dir }}/{{ item }}"
      state: absent
    with_items:
      - etcd-client.key
      - etcd-client.crt
      - etcd-ca.crt
      - etcd-client.csr

  - name: "Create secret {{ victoria_metrics_secret_name }} when it does not exist"
    command: "{{ kubectl }} --namespace {{ victoria_metrics_namespace }} create secret generic {{ victoria_metrics_secret_name }} --from-file={{ etcd_cert_config_dir }}"
    become: yes

  when: get_secret.rc != 0 and "NotFound" in get_secret.stderr

- name: Delete temp directory
  file:
    name: "{{ mktemp.stdout }}"
    state: absent
  become: yes
  changed_when: False
