- name: Get service Account status of Kube State Metrics
  shell: "{{ kubectl }} get serviceaccount -n {{ namespace_ksm }} {{ kube_state_metrics_name }}"
  register: serviceaccount_status
  become: yes
  failed_when: false == true

- name: Create service Account for Kube State Metrics
  when: serviceaccount_status.rc != 0
  block:
  - name: Create sa temp workspace directory
    command: mktemp -d /tmp/erikube-k8s-XXXXXX
    register: kubestatesatemp
    changed_when: False

  - name: Copy Service Account template for Kube State Metrics
    template:
      src: kube-state-metrics-serviceaccount.yaml.j2
      dest: "{{ kubestatesatemp.stdout }}/kube-state-metrics-serviceaccount.yaml"
    become: yes

  - name: Apply modified Kube State Metrics Service Account
    shell: "{{ kubectl }} apply -f {{ kubestatesatemp.stdout }}/kube-state-metrics-serviceaccount.yaml"
    become: yes

  - name: Delete SA temp directory
    file:
      name: "{{ kubestatesatemp.stdout }}"
      state: absent
    changed_when: False